<?xml version="1.0"?>
<!DOCTYPE adoptable_pets [
<!ELEMENT dog (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT breed (PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT cat (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT breed (PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT color (#PCDATA)>
]>

<adoptable_pets>
  <dog name="Jax">
    <age>Adult</age>
    <gender>Male</gender>
    <breed>German Shepherd Mix</breed>
    <size>Medium</size>
    <color>Brown/Chocolate</color>
  </dog>

  <dog name="Spot">
    <age>Adult</age>
    <gender>Male</gender>
    <breed>Chihuahua Mix</breed>
    <size>Small</size>
    <color>Tricolor (Brown, Black and White)</color>
  </dog>

  <cat name="Bellatrix">
    <age>Kitten</age>
    <gender>Female</gender>
    <breed>Domestic Medium Hair and Tabby Mix</breed>
    <size>Medium</size>
    <color>Brown/Chocolate</color>
  </cat>

  <cat name="John">
    <age>Senior</age>
    <gender>Male</gender>
    <breed>Tabby</breed>
    <size>Large</size>
    <color>Brown/Chocolate, White</color>
  </cat>

</adoptable_pets>
